#!/bin/bash

for pid in $(ps -axo pid)
do 
   if [[ !(-f "/proc/$pid/io") ]]; then continue; fi
   readbytes=$(cat /proc/"$pid"/io|grep -E "read_bytes.*"|awk '{print $2;}')
   if [[ "$readbytes" != "" ]];then
      echo "$pid $readbytes"
   fi
done > 7zero.txt

sleep 60
num=0
for pid in $(ps -axo pid)
do 
    if [[ !(-f "/proc/$pid/io") ]]; then continue; fi
   second=$(cat /proc/"$pid"/io|grep -E "read_bytes.*"|awk '{print $2;}')
   if [[ "$second" != "" ]];then  
     echo "$pid $second" 
   fi
done  > 7sixty.txt
IFS=$'\n'
for str in $(cat 7zero.txt)
   do
   pid=$(echo $str|awk '{print $1;}')
   val1=$(echo $str|awk '{print $2;}')
   val2=$(cat 7sixty.txt|grep -E "${pid} .*"|awk '{print $2;}'|head -1)
   ans=$(echo "scale=10; $val2-$val1" | bc) 
   echo "$pid $ans"
   done |sort -nrk2 |head -3 >out7.txt
for str in $(cat out7.txt)
do
pid=$(echo "$str"|awk '{print $1;}')
ans=$(echo "$str"|awk '{print $2;}')
cms=$(ps -p $pid -o cmd --no-headers)
echo "$pid : $cms : $ans"
done >outt7.txt
