#!/bin/bash
mkdir ~/test && echo "catalog test was created successfully" >~/report.tmp && touch ~/test/$(date +"%F_%R").tmp
ping -c 1 www.net_nikogo.ru || echo "$(date +"%F_%R") ERROR" >> ~/report.tmp
