#! /bin/bash
echo $$ > n6in
result=1
mode="+"
usr1()
{
mode="+"
}
usr2()
{
mode="*"
}
sigterm()
{
echo "sygterm stop"
exit
}
trap 'usr1' USR1
trap 'usr2' USR2
trap 'sigterm' SIGTERM
while true; do
case $mode in
"+")
cur=$(($cur + 2))
;;
"*")
cur=$(($cur * 2))
;;
esac
sleep 1
echo "$cur"
done
